### ISSUE TITLE
invalid memory error creating a cluster

### ISSUE THREAD

**Issue by carolynvs** [getcarina/carina#41]
I am using Caesious Caelum.

```
carina create mycluster --wait --nodes=1 --autoscale

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x40701b]

goroutine 1 [running]:
main.(*WaitClusterCommand).clusterApplyWait(0xc082009510, 0xc082065c88, 0x2e0028, 0xc0821699e0)
        /go/src/github.com/getcarina/carina/main.go:292 +0x2cb
main.(*CreateCommand).Create(0xc0820070a0, 0xc08206ea80, 0x0, 0x0)
        /go/src/github.com/getcarina/carina/main.go:329 +0x51
main.(*CreateCommand).Create-fm(0xc08206ea80, 0x0, 0x0)
        /go/src/github.com/getcarina/carina/main.go:120 +0x3f
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc082058120, 0xc08206ea80, 0x0, 0x0)
        /go/src/gopkg.in/alecthomas/kingpin.v2/actions.go:28 +0x82
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc0820860e0, 0xc08206ea80, 0x0, 0x0)
        /go/src/gopkg.in/alecthomas/kingpin.v2/app.go:511 +0x162
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc0820860e0, 0xc08206ea80, 0x0, 0x0, 0x0, 0x0)
        /go/src/gopkg.in/alecthomas/kingpin.v2/app.go:353 +0x257
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc0820860e0, 0xc082010310, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0)
        /go/src/gopkg.in/alecthomas/kingpin.v2/app.go:156 +0x1f0
main.main()
        /go/src/github.com/getcarina/carina/main.go:420 +0x84

goroutine 12 [IO wait]:
net.runtime_pollWait(0x2e57b0, 0x72, 0xc0821699d0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc08201d7f0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082026208, 0xc08201d6e0, 0x87b278, 0x7, 0x939998, 0x14b, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc08201d680, 0xc082146400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc082026290, 0xc082146400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xeb
crypto/tls.(*block).readFromUntil(0xc08212f680, 0x2e5870, 0xc082026290, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:455 +0xd3
crypto/tls.(*Conn).readRecord(0xc082069600, 0x93a017, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:540 +0x2d8
crypto/tls.(*Conn).Read(0xc082069600, 0xc082149000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:901 +0x16e
net/http.noteEOFReader.Read(0x3903a8, 0xc082069600, 0xc082089188, 0xc082149000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x6e
net/http.(*noteEOFReader).Read(0xc08216bdc0, 0xc082149000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd7
bufio.(*Reader).fill(0xc082170540)
        /usr/local/go/src/bufio/bufio.go:97 +0x1f0
bufio.(*Reader).Peek(0xc082170540, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xd3
net/http.(*persistConn).readLoop(0xc082089130)
        /usr/local/go/src/net/http/transport.go:876 +0xfe
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc7f

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc082089130)
        /usr/local/go/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xca4
```

**Comment by smashwilson** [comment]
Weird, I'm seeing sporadic failures from the `create` call too, but it seems inconsistent:

```
$ ./carina create something --wait --nodes=1 --autoscale
carina: error: Get https://app.getcarina.com/clusters/dse.ashwilson/something: EOF, try --help
$ ./carina create something --wait --nodes=1 --autoscale
something	container1-4G	1	true	active
```

I'm wondering if it has something to do with work upstream.

**Comment by rgbkrk** [comment]
I've noticed that sometimes with `--wait` but I haven't figured out why or how we'd catch it yet.

**Comment by rgbkrk** [comment]
Fixed by #62. Care to take it for a spin @carolynvs?

**Comment by carolynvs** [comment]
Sure will do!

**Comment by carolynvs** [comment]
I just made and deleted 2 clusters using `--wait` and it worked great. :cake:
